<a href="https://colab.research.google.com/github/Archalharin/229352-stat-for-data-science/blob/main/660510632_02_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [2]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a= torch.tensor(2)
a

tensor(2)

In [ ]:
b= torch.tensor(3)
a * b

tensor(6)

### Convert a tensor to scalar

In [ ]:
c = b.item() #เปลี่ยนจาก tensor เป็นตัวเลขธรรมดา
c

3

### Creating 2D tensor

In [ ]:
A = torch.tensor([[1, 2],[5,6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
B = A.numpy() #tensor to array
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [ ]:
C = torch.from_numpy(B) #array to tensor
C

tensor([[1, 2],
        [5, 6]])

## Basic operations

In [ ]:
E * 2

array([[ 2,  4],
       [10, 12]])

In [ ]:
E - 2

array([[-1,  0],
       [ 3,  4]])

In [ ]:
E * np.array([1, 2])

array([[ 1,  4],
       [ 5, 12]])

In [ ]:
D * 2

tensor([[ 2,  4],
        [10, 12]], device='cuda:0')

In [ ]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [ ]:
A = torch.tensor([[4, 5],[8,9]])
B = torch.tensor([[1,4],[7,8]])
##1
torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
##2
torch.mm(A, B) #torch.matmul(A, B) = torch.mm(A, B) คูณเมทริกซ์

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
##3
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [ ]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(1,2,3) #tensor 3 มิติ
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
b = torch.ones(1,2,3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
I = torch.eye(3) # เมทริกซ์เอกลักษณ์
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
R1 = torch.rand(2,3) # สุ่มเลขจากการแจกแจง Uniform
R1

tensor([[0.7170, 0.4841, 0.7008],
        [0.8340, 0.3364, 0.4106]])

In [ ]:
R2 = torch.randn(2,3) # สุ่มเลขจากการแจกแจง Normal
R2

tensor([[ 0.6114,  0.6127,  1.0742],
        [-0.3902,  2.5355, -2.1407]])

In [ ]:
a = torch.arange(6) #เลขเรียงลำดับ
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [ ]:
A.shape

torch.Size([2, 2])

In [ ]:
A.size() #A.shape

torch.Size([2, 2])

### Checking the shape of a tensor

In [ ]:
u = torch.arange(6)
u.shape

torch.Size([6])

### Changing the shape of a tensor

In [ ]:
v = u.reshape(2, 3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [ ]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
# concatenate
e = torch.cat([a, b], axis=0)  # 1มิติ รวม 1 มิติ ยังจะได้ 1 มิติอยู๋
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [ ]:
f = torch.cat([a, b], axis=1)  # 1มิติ รวม 1 มิติ ยังจะได้ 1 มิติอยู๋ แต่ cat 1 มิติใช้ axis=1 ไม่ได้
f

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(1, 2, 3)
B = A.squeeze() # ลบ 1 แกน
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
B.shape

torch.Size([2, 3])

In [ ]:
# H.shape = (6, )
L = H.unsqueeze(axis=0)  # L.shape(1, 6)
M = H.unsqueeze(axis=1)  # L.shape(6, 1)
print(L)
print(M)

### UnSqueezing a tensor (adding an extra dimension)

In [ ]:
d = B.unsqueeze(axis=0)
d

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
P[[0, 1, 2], [0,1,2]]
P[0:3,0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available() #T4 CPU

True

In [ ]:
C.device

device(type='cpu')

In [ ]:
D = C.cuda() # สร้างcopyของC แต่วางที่ GPU
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [ ]:
D.device

device(type='cuda', index=0)

In [ ]:
# D.numpy()

E = D.cpu().numpy()

E

array([[1, 2],
       [5, 6]])

In [ ]:
R = Q.to('cuda')
print(Q.device)
print(R.device)

In [ ]:
R.cpu().numpy()

In [ ]:
torch.inverse(torch.tensor([[2.0, 0.0],[0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [3]:
#1
#X.shape = (200, 7)
X = torch.randn(200, 7)

#b.shape = (8, 1)
b = torch.randn(8, 1)

#e.shape = (200, 1)
e = torch.randn(200, 1)

In [4]:
X.shape

torch.Size([200, 7])

In [5]:
#Create a tensor that contains only 1's
ONES = torch.ones(200, 1)

In [6]:
#adding the tensor in 2. as the first column
X = torch.cat([ONES, X], axis=1)
X

tensor([[ 1.0000, -0.0219, -0.3827,  ..., -0.7997, -0.4382,  0.6836],
        [ 1.0000,  1.8132,  0.8199,  ..., -1.3314,  1.0296, -0.2711],
        [ 1.0000, -0.1777, -0.3152,  ...,  0.4810, -0.9997,  0.4622],
        ...,
        [ 1.0000,  1.1111,  0.6776,  ...,  1.2372,  1.3242,  0.4192],
        [ 1.0000,  0.4616,  0.4353,  ...,  0.0174,  0.8441,  0.3958],
        [ 1.0000, -0.4720,  0.1148,  ...,  0.2288,  0.3253,  0.2971]])

In [8]:
X.shape

torch.Size([200, 8])

In [7]:
#liner regession
y = X @ b + e

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)



LinearRegression()

In [10]:
#b_hat
b_hat = torch.inverse(X.T @ X) @ X.T @ y

In [11]:
#y_hat
y_hat = X @ b_hat

In [12]:
 #Numpy array and calculate MSE
y = y.numpy()
y_hat = y_hat.numpy()

In [13]:
MSE = 1 / 200 * np.sum(y - y_hat)** 2
MSE

np.float32(1.1368684e-15)

In [ ]:
X1 = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X1)

X2 = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X2)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
X1.shape

torch.Size([3, 3])

In [ ]:
X2.shape

torch.Size([3, 4])

In [ ]:
X1 = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
b1 = torch.randn(4,1)
e1 = torch.randn(3,1)
ONES1 = torch.ones(3, 1)
X1 = torch.cat([ONES1, X1], axis=1)
y1 = X1 @ b1 + e1
b_hat1 = torch.inverse(X1.T @ X1) @ X1.T @ y1
y_hat1 = X1 @ b_hat1

y1 = y1.numpy()
y_hat1 = y_hat1.numpy()

MSE1 = 1 / 200 * np.sum(y1 - y_hat1)** 2
MSE1

np.float32(0.0789118)

In [ ]:
X2 = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]], dtype=torch.float32)
b2 = torch.randn(4,1)
e2 = torch.randn(3,1)
# ONES2 = torch.ones(3, 1)
# X2 = torch.cat([ONES2, X2], axis=1)
y2 = X2 @ b2 + e2
b_hat2 = torch.inverse(X2.T @ X2) @ X2.T @ y2
y_hat2 = X2 @ b_hat2

y2 = y2.numpy()
y_hat2 = y_hat2.numpy()

MSE2 = 1 / 200 * np.sum(y2 - y_hat2)** 2
MSE2

np.float32(0.66288406)